services:
  dev-qwik-app:
    extends:
      file: docker-compose.yml
      service: my-qwik-app
    volumes:
      - node_modules_cache:/app/node_modules/
      - ./:/app
    command: sh -c "npm install &&  npm run dev"


volumes:
  node_modules_cache:
