services:
  dev-qwik-app:
    extends:
      file: docker-compose.yml
      service: my-qwik-app
    volumes:
      - node_modules_cache:/app/node_modules/
      - ./:/app
    command: sh -c "npm install &&  npm run dev"


volumes:
  node_modules_cache:

# Mount local volume to /app for hot reloading
# Cache node_modules for faster setting up
# Overwrite run command to install missing dependencies and run npm run dev instead